openapi: 3.0.3
info:
  title: OpenAPI schema for Prometheus template .
components:
  schemas:
    variables:
      type: object
      properties:
        release_name:
          title: Release Name
          type: string
          description: The name of the Helm release.
          default: prometheus
          x-walrus-ui:
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: prometheus-system
          x-walrus-ui:
            group: Basic
            order: 2
        chart_version:
          title: Chart Version
          type: string
          description: The version of the Prometheus Helm chart.
          default: 64.0.0
          x-walrus-ui:
            group: Basic
            order: 3
        channel_teams:
          title: Channel Teams
          type: string
          description: Channel Microsoft Teams
          default: alerts_dev-stg
          x-walrus-ui:
            group: Basic
            order: 4
        domain_name:
          title: Domain Name
          type: string
          description: Domain name for Harbor, e.g. 'dev.domainname.com'
          default: dev.domainname.com
          x-walrus-ui:
            group: Basic
            order: 5
        issuer_name:
          title: Issuer Name
          type: string
          description: Origin issuer name
          default: origin-ca-issuer
          x-walrus-ui:
            group: Basic
            order: 6
        issuer_kind:
          title: Issuer Kind
          type: string
          description: Origin issuer kind
          default: ClusterOriginIssuer
          x-walrus-ui:
            group: Basic
            order: 7
        grafana_enabled:
          title: Grafana Enabled
          type: boolean
          description: Grafana Enabled
          default: "false"
          x-walrus-ui:
            group: Basic
            order: 8
        grafana_ingress_enabled:
          title: Grafana Ingress Enabled
          type: boolean
          description: Grafana Ingress Enabled
          default: "false"
          x-walrus-ui:
            group: Basic
            order: 9
        whitelist_ips:
          title: Whitelist Ips
          type: array
          description: List of IP addresses to be whitelisted
          default:
          - 192.168.1.1
          - 192.168.1.2
          - 192.168.1.3
          items:
            type: string
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 10
      x-walrus-ui:
        groupOrder:
        - Basic
