openapi: 3.0.3
info:
  title: OpenAPI schema for Prometheus template .
components:
  schemas:
    variables:
      type: object
      properties:
        release_name:
          title: Release Name
          type: string
          description: The name of the Helm release.
          default: prometheus
          x-walrus-ui:
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: prometheus-system
          x-walrus-ui:
            group: Basic
            order: 2
        chart_version:
          title: Chart Version
          type: string
          description: The version of the Prometheus Helm chart.
          default: 64.0.0
          x-walrus-ui:
            group: Basic
            order: 3
        prometheus_values:
          title: Prometheus Values
          type: string
          description: Raw URL with the values file for Prometheus HelmChart, more
            info https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=values
          default: https://raw.githubusercontent.com/cuemby-labs/infra-terraform-prometheus/refs/tags/v1.0.7/values.yaml
          x-walrus-ui:
            group: Basic
            order: 4
      x-walrus-ui:
        groupOrder:
        - Basic
