openapi: 3.0.3
info:
  title: OpenAPI schema for Prometheus template .
components:
  schemas:
    variables:
      type: object
      properties:
        release_name:
          title: Release Name
          type: string
          description: The name of the Helm release.
          default: prometheus
          x-walrus-ui:
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: prometheus-system
          x-walrus-ui:
            group: Basic
            order: 2
        chart_version:
          title: Chart Version
          type: string
          description: The version of the Prometheus Helm chart.
          default: 64.0.0
          x-walrus-ui:
            group: Basic
            order: 3
        secrets:
          title: Secrets
          type: array
          description: List of secrets with username and password
          default:
          - password: password1
            username: user1
          - password: password2
            username: user2
          items:
            properties:
              password:
                title: Password
                type: string
                x-walrus-ui:
                  order: 2
              username:
                title: Username
                type: string
                x-walrus-ui:
                  order: 1
            required:
            - password
            - username
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 4
        set_custom_values:
          title: Set Custom Values
          type: boolean
          description: Set custom values
          default: false
          x-walrus-ui:
            group: Basic
            order: 5
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for Prometheus Helm release.
          default:
            alertmanager:
              limits:
                cpu: 200m
                memory: 800Mi
              requests:
                cpu: 100m
                memory: 400Mi
            operator:
              limits:
                cpu: 200m
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi
            prometheus:
              limits:
                cpu: 200m
                memory: 800Mi
              requests:
                cpu: 100m
                memory: 400Mi
          additionalProperties:
            properties:
              limits:
                properties:
                  cpu:
                    title: Cpu
                    type: string
                    x-walrus-ui:
                      order: 1
                  memory:
                    title: Memory
                    type: string
                    x-walrus-ui:
                      order: 2
                required:
                - cpu
                - memory
                title: Limits
                type: object
                x-walrus-ui:
                  colSpan: 12
                  order: 1
              requests:
                properties:
                  cpu:
                    title: Cpu
                    type: string
                    x-walrus-ui:
                      order: 1
                  memory:
                    title: Memory
                    type: string
                    x-walrus-ui:
                      order: 2
                required:
                - cpu
                - memory
                title: Requests
                type: object
                x-walrus-ui:
                  colSpan: 12
                  order: 2
            required:
            - limits
            - requests
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
        values:
          title: Values
          type: object
          description: Chart values for Prometheus HelmChart, more info https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=values
          default: {}
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 7
            widget: YamlEditor
        hpa_config:
          title: Hpa Config
          type: object
          description: Configuration for the HPA targeting Prometheus Deployment
          default:
            max_replicas: 3
            min_replicas: 1
            target_cpu_utilization: 80
            target_memory_utilization: 80
          required:
          - max_replicas
          - min_replicas
          - target_cpu_utilization
          - target_memory_utilization
          properties:
            max_replicas:
              title: Max Replicas
              type: number
              x-walrus-ui:
                order: 2
            min_replicas:
              title: Min Replicas
              type: number
              x-walrus-ui:
                order: 1
            target_cpu_utilization:
              title: Target Cpu Utilization
              type: number
              x-walrus-ui:
                order: 3
            target_memory_utilization:
              title: Target Memory Utilization
              type: number
              x-walrus-ui:
                order: 4
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 8
      x-walrus-ui:
        groupOrder:
        - Basic
